ALTER TABLE S ADD 选课门数 INT;

SELECT SNO
FROM VIEW1
WHERE AGE=19;
SELECT SNAME
FROM VIEW2
WHERE BIRTHYEAR=2004;
SELECT SNO,SNAME
FROM VIEW3
WHERE SNO='S10';
SELECT SNO,SNAME
FROM VIEW4
WHERE NUMOFCLASS>2;

ALTER TABLE S DROP COLUMN 选课门数;