use studb
CREATE TABLE S
		(SNO CHAR(6) PRIMARY KEY,
		SNAME CHAR(8) NOT NULL,
		AGE SMALLINT,
		SEX CHAR(1),
		DNAME VARCHAR(12));

CREATE TABLE C
		(CNO CHAR(2) NOT NULL,
		CNAME VARCHAR(24) NOT NULL,
		CREDIT SMALLINT,
		PRE_CNO CHAR(2),
		PRIMARY KEY(CNO));

CREATE TABLE SC
			( SNO CHAR(6) NOT NULL,
			  CNO CHAR(2) NOT NULL,
			  SCORE SMALLINT,
			  PRIMARY KEY(SNO,CNO),
			  FOREIGN KEY(SNO)
							REFERENCES S ON DELETE CASCADE,
			  FOREIGN KEY(CNO)
							REFERENCES C ON DELETE NO ACTION);