CREATE TABLE Doctor(
	dID CHAR(10) PRIMARY KEY,
	dName VARCHAR(50),
	Title VARCHAR(50),
	Department VARCHAR(50));

CREATE TABLE Patient(
	pID CHAR(10) PRIMARY KEY,
	pName VARCHAR(50),
	sex CHAR(4),
	Birth DATE);

CREATE TABLE Cure(
	dID CHAR(10),
	pID CHAR(10),
	Fee FLOAT,
	PRIMARY KEY (dID,pID),
	FOREIGN KEY (dID) REFERENCES Doctor(dID),
	FOREIGN KEY (pID) REFERENCES Patient(pID));