DROP TABLE itb1;
CREATE TABLE itb1(
id BIGINT IDENTITY(1,1) NOT NULL,
rq DATETIME NULL,
srq VARCHAR(20) NULL,
hh SMALLINT NULL,
mm SMALLINT NULL,
ss SMALLINT NULL,
num NUMERIC(12,3))

DECLARE @i INT
SELECT @i =1
WHILE @i<=500000
BEGIN 
	INSERT INTO itb1(rq,srq,hh,mm,ss,num)
	VALUES(GETDATE(),CAST(GETDATE() AS VARCHAR(20)),
	DATEPART(hh,GETDATE()),DATEPART(mi,GETDATE()),
	DATEPART(ss,GETDATE()),cast(RAND(@i)*100 AS numeric(12,3)))
	SELECT @i = @i + 1
END