--创建一个存储过程SPJInfo，
--在S表、P表、J表、SPJ表中查询
--工程项目代码、工程项目名、
--零件代码、零件名、颜色、
--供应商代码、供应商姓名

IF EXISTS (
	SELECT NAME FROM SYSOBJECTS
	WHERE NAME='SPJInfo' AND TYPE='P')
DROP PROCEDURE SPJInfo
GO
CREATE PROCEDURE SPJInfo AS
SELECT SPJ.JNO,JNAME,SPJ.PNO,PNAME,COLOR,SPJ.SNO,SNAME
FROM S,P,J,SPJ
WHERE S.SNO=SPJ.SNO AND P.PNO=SPJ.PNO AND
		J.JNO=SPJ.JNO