--创建一个存储过程GET_QTY_BY_P，
--在S表、P表、J表、SPJ表中查询
--某工程指定配件的配件的供应商和数量
IF EXISTS (
	SELECT NAME FROM SYSOBJECTS
	WHERE NAME='GET_QTY_BY_P' AND TYPE='P')
DROP PROCEDURE GET_QTY_BY_P
GO
CREATE PROCEDURE GET_QTY_BY_P(
	@JNO VARCHAR(50),
	@PNO VARCHAR(50))
AS
SELECT S.SNAME,QTY
FROM S,P,J,SPJ
WHERE S.SNO=SPJ.SNO AND P.PNO=SPJ.PNO AND
	J.JNO=SPJ.JNO AND J.JNO=@JNO AND P.PNO=@PNO