INSERT INTO SPJ(SNO,PNO,JNO,QTY) 
VALUES
	('S1','P1','J2',50);
INSERT INTO SPJ(SNO,PNO,JNO,QTY) 
VALUES
	('S3','P3','J3',-1);
INSERT INTO SPJ(SNO,PNO,JNO,QTY) 
VALUES
	('S3','P1','J3',100000);

UPDATE SPJ SET QTY=-5
WHERE SNO='S1' AND PNO='P1' AND JNO='J2'