--创建AFTER触发器：
--在SPJ表上创建一个插入、更新类型的触发器TR_QTYCheck,
--当在 QTY 字段中插入或修改考试分数后,
--触发该触发器，检查分数是否在 0-10000 之间。
IF EXISTS(SELECT NAME FROM SYSOBJECTS 
WHERE NAME='TR_QTYCheck' AND TYPE='TR')
DROP TRIGGER TR_QTYCheck
GO
CREATE TRIGGER TR_QTYCheck ON SPJ
FOR INSERT,UPDATE AS
IF UPDATE(QTY) PRINT 'AFTER触发器开始执行……'
BEGIN
	DECLARE @QTY REAL
	SELECT @QTY=(SELECT QTY FROM INSERTED)
	IF @QTY<0 OR @QTY>1000
	PRINT '输入的数量有误，请确认输入的零件数量！'
END
GO