--为 S 表创建一个名为TRI_DE_S的后触发器，
--当删除某条记录时，自动检查表SPJ中是否有该供应商的记录，
--如果存在则取消删除操作。
IF EXISTS (SELECT NAME FROM SYSOBJECTS 
			WHERE NAME='TRI_DE_S' AND TYPE='TR')
DROP TRIGGER TRI_DE_S
GO

CREATE TRIGGER TRI_DE_S ON S 
FOR DELETE
AS
BEGIN
	DECLARE @SNO VARCHAR(50)
	SELECT @SNO=(SELECT SNO FROM DELETED)
	IF EXISTS(SELECT SNO FROM SPJ WHERE SNO=@SNO)
	BEGIN
		PRINT 'SPJ存在供应记录，禁止删除'
		ROLLBACK TRAN
	END
END