CREATE TABLE S(
	SNO CHAR(4) PRIMARY KEY,
	SNAME VARCHAR(50),
	STATUS INT,
	CITY VARCHAR(50)
)

CREATE TABLE P(
	PNO CHAR(4) PRIMARY KEY,
	PNAME VARCHAR(50),
	COLOR VARCHAR(50),
	WEIGHT INT
)

CREATE TABLE J(
	JNO CHAR(4) PRIMARY KEY,
	JNAME VARCHAR(50),
	CITY VARCHAR(50)
)
CREATE TABLE SPJ(
	SNO CHAR(4),
	PNO CHAR(4),
	JNO CHAR(4),
	PRIMARY KEY (SNO,PNO,JNO),
	FOREIGN KEY (SNO) REFERENCES S(SNO),
    FOREIGN KEY (PNO) REFERENCES P(PNO),
	FOREIGN KEY (JNO) REFERENCES J(JNO),
	QTY INT
)